[toolchain]
channel = "stable"
components = ["rustfmt", "rustc-dev", "rust-src"]
targets = [
    "wasm32-unknown-unknown",
    "aarch64-apple-darwin",
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "aarch64-linux-android",
    "x86_64-apple-ios",
]
profile = "minimal"
