[package]
name = "mtmd"
version = "0.1.86"
edition = "2021"
publish = false

[dependencies]
infrastructure_llama_cpp = { workspace = true, features = ["mtmd"]  }
clap = { workspace = true, features = ["derive"] }

[features]
cuda = ["infrastructure_llama_cpp/cuda"]
metal = ["infrastructure_llama_cpp/metal"]
vulkan = ["infrastructure_llama_cpp/vulkan"]

[lints]
workspace = true

[[example]]
name = "mtmd"
path = "src/mtmd.rs"
