[package]
name = "simple"
version = "0.1.131"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infrastructure_llama_cpp = { workspace = true }

hf-hub = { version = "0.4.3" }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
encoding_rs = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
cuda = ["infrastructure_llama_cpp/cuda"]
metal = ["infrastructure_llama_cpp/metal"]
vulkan = ["infrastructure_llama_cpp/vulkan"]

[lints]
workspace = true
