[package]
name = "foundation_ai"
version = "0.0.3"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "AI foundation create for the eweplatform"
keywords = ["foundations_ai", "ewe-platform-ai"]

[dependencies]

# -- Workspace dependencies

foundation_nostd = {workspace = true }

